### PR TITLE
Added commands that work with windows/cygwin

### PR DESCRIPTION
**Pull request by m42e**
Works at least with windows 7.

### CODE REVIEW

**Comment by bruno-** [comment]
Hey,
thanks for contributing.
Can you please make the following changes/additions:

- add yourself to the contributors list in the readme
- add a one-line description to `CHANGELOG.md`
- are tabs used for code indentation? If not, pls change to tabs.
- squash everything to a single commit

**Comment by m42e** [comment]
Done

**Comment by m42e** [comment]
Please do not merge, It causes high CPU Load.. Windows is so ....

**Comment by bruno-** [comment]
Hey, what is your `tmux show -g status-interval`? Could it be that one is set too low (like below 5 seconds) so that's choking it?

**Comment by m42e** [comment]
It is set to 5 seconds but it pikes to about 50% on all my 4 cores. I don't think that good, when running on battery :(
cpuload

**Comment by bruno-** [comment]
That's unfortunate .. let's leave the PR open for now and see if this gives someone an inspiration to try to optimize this.

**Comment by m42e** [comment]
Well it looks like it is not wmic itself, I tried to read it using a self compiled tool and the windows API and even a fixed string. It seems the processing within bash takes that much performance.

**Comment by bruno-** [comment]
Hm.. that's interesting.. a small bash script choking 4 processor cores.

All tmux really does is call this script every 5 seconds (if that's your `status-interval`).
Do you have time to test the script so we can narrow down the issue?

This would be the steps:

- go to `tmux-battery` directory on your system
- make sure `scripts/battery_percentage.sh` contains changes from this PR (windows support)
- run `scripts/battery_percentage.sh` script to make sure you get battery percentage on the output
- test calling a script with this one-liner and see what happens with CPU: `while true; do scripts/battery_percentage.sh; sleep 5; done`

**Comment by m42e** [comment]
Well someone else might give it a try to, maybe it is only a local issue.

**Pull request closed without merging**
