### PR TITLE
Adds support for changing bg color based on battery percentage.

### PR DESCRIPTION
**Pull request by RyanFrantz**
If `#{battery_status_bg}` is used, the background of this plugin's status bar will be:
- 'green' for 100% charged
- 'yellow' for 99% to 51% charge
- orange ('colour208') for 50% to 16% charge
- 'red' for 15% to 0% charge

### CODE REVIEW

**Comment by martinbeentjes** [comment]
Nice feature, maybe you could implement the possibility of defining the ranges for the colors with settings? So an user can customize these in a more user-friendly way?

**Comment by RyanFrantz** [comment]
As an example, are you referring to something like this bit of code?

https://github.com/tmux-plugins/tmux-battery/blob/master/scripts/battery_icon.sh#L7-L17

**Comment by martinbeentjes** [comment]
I mean, the possibility that an user can configure the intervals by settings variables in their own tmux configuration file. I actually mean lines [28 to 33](https://github.com/tmux-plugins/tmux-battery/blob/master/scripts/battery_icon.sh#L28-L33) (see the helpers.sh for the `get_tmux_option`.

Just so when an user does not like the (for me most logical) standard colorscheme as you described it, they can adjust it to their likings.

**Comment by RyanFrantz** [comment]
Y'know, the code you linked to was what I really meant to refer to! ;)

I'll get on that now.

**Comment by martinbeentjes** [comment]
Thanks for your contribution! :-)

**Pull request merged**
