### PR TITLE
add highlighting battery percentage

### PR DESCRIPTION
**Pull request by knakayama**
This PR is same #13. But high CPU Load may be not seen.

### CODE REVIEW

**Comment by bruno-** [comment]
Thanks for the contribution. After thinking about this, I personally would like to have this feature, so let's work in getting this merged.

Question: what if the user wants to highlight the `#{battery_remain}` output in addition to percentage when battery is low? That is not possible with this PR I presume?

Also, maybe someone would like to change the background color when the battery is low?

What do you think about the following interface:

    "#[battery_low_fg=red]#{battery_percentage}#[fg=default]"

and also:

    "#[battery_low_bg=red]#{battery_remain}#[bg=default]"

**Comment by bruno-** [comment]
The above will be more challenging to implement but it's completely decoupled from `#{battery_percentage}` - it can be used for anything in `status-right` or `status-left`.

**Comment by knakayama** [comment]
@bruno- 
Thanks for your review. I agree with your advises. I try to implement the features.

**Comment by bruno-** [comment]
Great. Let me know if you get stuck or you need help!

**Comment by knakayama** [comment]
Sorry for late reply.

Implementing this PR is a little hard to me. #16 is looks like a great PR for me. So I close this PR. Sorry.

**Pull request closed without merging**
