### PR TITLE
Add support for OS X "attached" battery state

### LINKED ISSUE #3: Doesn't handle "attached" state
I've discovered an unhandled battery state. My MacBook charging cable was plugged in, but it was a little loose and the light wasn't on.

```sh
~$ pmset -g batt
Now drawing from 'AC Power'
 -InternalBattery-0	2%; AC attached; not charging
```

`battery_icon` is blank in this scenario because that state (neither charging nor discharging) is [not accounted for](https://github.com/tmux-plugins/tmux-battery/blob/master/scripts/battery_icon.sh#L42-L51). Maybe it can be handled by creating `@batt_attached_icon` defaulted to one of these?

- :snail:
- :boom:
- :wavy_dash:
- :electric_plug:
- :neutral_face:
- :warning:

### PR DESCRIPTION
**Pull request by m1foley**
Fixes #3.

It might deserve a screenshot as well, but I'll leave that up to you.

### CODE REVIEW

**Comment by m1foley** [comment]
I made this change because I'd prefer to know when my charging cable doesn't have a solid connection (happens more frequently than you'd expect on Macs). But it won't hurt my feelings if you close this PR because you prefer the old blank behavior ;)

**Comment by bruno-** [comment]
Thank you for the contribution sir!

> if you close this PR because you prefer the old blank behavior ;)

No way, I really like this addition. I wasn't aware this state can happen when charging (although it did happen to me once). It's very useful to know when you \*think* your mac is charging, but in fact it's \*not* charging.

I do have one thing to ask - would you mind if I changed the default icon to :warning:? I feel that one would indicate more correctly there is something unexpected going on. Snail would, in this case indicate things are moving forward, but slowly (which I think is not the case here).

Anyway, you think that okay?

**Comment by m1foley** [comment]
Yes, that sounds good to me -- I agree with your preference now that I think about it some more.

FWIW, I went with :snail: because:

- I've experienced slow charges under these conditions.
- :warning: might be interpreted as something more severe, like a broken battery.

Here's why I'm changing my mind:

- It might not actually be charging at all so :snail: could be inaccurate.
- Like you mentioned, :warning: more accurately indicates an error condition that users want to be alerted to.
- Fears of a broken battery will be assuaged when they simply examine their cable and see that it's loose.

**Comment by bruno-** [comment]
Great, it's updated now!

**Comment by m1foley** [comment]
Maybe the alternate in the README should be changed from :neutral_face: to :confused:

**Pull request merged**
