### PR TITLE
Add battery remaining time interpolation

### PR DESCRIPTION
**Pull request by asethwright**
This works fine on my Mac (using psmet). This may need further modification for upower (i'm not sure of the upower output).

### CODE REVIEW

**Comment by JanAhrens** [comment]
Hi @asethwright,

I checked this on my Ubuntu machine with upower 0.9.23. The field in the upower output is called "time to empty". Unfortuanetly the output is a little bit too fancy and the authors decided to include "minutes" and "hours" as a string. I decided to have this in the output to not confuse people ("55" is not as descriptive as "55 minutes").
 
This following snippet works for me. I already included multiple battery support that I'm suggesting in #7. Maybe you want to incorporate it in this pull-request.

```
for battery in $(upower -e | grep battery); do
  upower -i $battery | grep 'time to empty' | awk '{print $4 " " $5}' 
done
```

Cheers, Jan

**Comment by JanAhrens** [comment]
I'm not 100% convinced that it's a good thing that the upower output contains "hours" and "minutes". I tried to get upower to output the time in seconds, but there is currently no option to do this:

The function that generates the output in [up-device.c:496](http://cgit.freedesktop.org/upower/tree/libupower-glib/up-device.c?id=90df3546b05a27b21411cb487d171e8f4060f035#n496) will always generate a [formatted string](http://cgit.freedesktop.org/upower/tree/libupower-glib/up-device.c?id=d8e9f2b98b9c22357cf4a8beb44d034cd9d91b97#n400) with "seconds", "minutes", "hours" and even "days" (those people planned ahead .. I wish I had such a huge battery capacity today).

To solve this I see three options:
- Leave everything as it is. "Minutes" and "hours" in the output are not that bad in the end.
- Parse to output and convert everything to seconds and from there to the format we like.
- Use another way to get this info on Linux. There might be a way to get those information from `/sys/class/power_supply/BAT0`. IMHO this is a bad option as it excludes Non-Linux users.

What do others think about the "remaining time" output for Non-OSX systems?

**Comment by JanAhrens** [comment]
You can get the remaining seconds when you directly query dbus. It's not looking pretty, but at least it's using the [documented interface](http://upower.freedesktop.org/docs/Device.html#Device:TimeToEmpty). Other people are also using [this method](https://gitorious.org/opensuse/pm-utils/source/ff5e1d127a26b3b9d1034442c04f727d4fe0bce6:bin/powersave#L204) ..

```bash
for battery in $(upower -e | grep battery); do
  dbus-send --print-reply=literal --system \
    --dest=org.freedesktop.UPower $battery \
    org.freedesktop.DBus.Properties.Get string:org.freedesktop.UPower \
    string:TimeToEmpty \
  | awk '{print $3}'
done
```

I'll wait for feedback before doing more work here ..

**Comment by asethwright** [comment]
Hey @JanAhrens... Sorry for my delay. Has been a busy week for my family.

Your code above looks great and can probably be added as a helper function. Looks like with this implementation, we can format the time as we see fit. It allows for the most flexibility. This would even potentially allow for formatting options later (i.e. someone may only care about how many hours remain to simplify their tmux statusline).

I'll take your word on the implementation of this... Tried to get a Linux virtual machine to respond to a upower command with no luck.

My only additional feedback would be that we should try to keep defaults the same... So since mac prints out HH:MM by default, we should convert the upower output to HH:MM (or DD::HH:MM, which, I also hope I can use personally sometime soon). Don't think we need to be so specific as to provide seconds, which is probably inaccurate anyways.

Maybe we can add the following as a helper function?

```
function show_time () {
    num=$1
    min=0
    hour=0
    day=0
    if((num>59));then
        ((sec=num%60))
        ((num=num/60))
        if((num>59));then
            ((min=num%60))
            ((num=num/60))
            if((num>23));then
                ((hour=num%24))
                ((day=num/24))
            else
                ((hour=num))
            fi
        else
            ((min=num))
        fi
    else
        ((sec=num))
    fi
    echo "$day":"$hour":"$min"
}

// http://stackoverflow.com/questions/12199631/convert-seconds-to-hours-minutes-seconds-in-bash
```

```
1:23
```

Also, one more note... the mac automatically switches the output of `pmset -g batt` to show the time remaining until a full charge. We can perhaps add a conditional to check this state on upower.

```
The "TimeToFull" property

'TimeToFull'  read      'x'
Number of seconds until the power source is considered full. Is set to 0 if unknown.

This property is only valid if the property type has the value "battery".

// http://upower.freedesktop.org/docs/Device.html
```

**Comment by bruno-** [comment]
@asethwright, thanks - this is a really nice feature!
I'm merging it because I wanna use it right away :smile:

**Comment by bruno-** [comment]
@JanAhrens feel free to open a pull request that will make "battery_remain" have properly formatted output.

**Pull request merged**
