### PR TITLE
Range formatting and graph

### PR DESCRIPTION
**Pull request by levens**
This is my own independent implementation similar to PR #13 & #14. It implements three level highlighting using two format strings `#{battery_prefix}` and `#{battery_suffix}` which surround the highlighted part of `status-right` or `status-left`. The exact strings to be substituted can be customised, for example to change the foreground/background colours (default green/yellow/red) and the threshold levels can be changed (default >=30% green, <30% yellow, <10% red).

A second new feature is a [spark](https://github.com/holman/spark) inspired graph showing the battery level as a single character (▁▂▃▅▇).

### CODE REVIEW

**Comment by levens** [comment]
Any chance of having this PR merged?

**Comment by martinbeentjes** [comment]
Currently, functionality on changing fore- and background based upon the percentage of the battery is already implemented. I will close this for now, thanks for your input anyway. Maybe I'll get back to this in the future.

**Comment by levens** [comment]
Hi @martinbeentjes,

It is a shame that @RyanFrantz is re-implementing what I did already ~2 years ago.

I have opened #37 to salvage the remaining features which have not been re-implemented.

Cheers,

**Comment by martinbeentjes** [comment]
I understand your concern, however I saw @RyanFrantz his PR other than yours. Therefore I merges his first, was not really sure what to think of your contribution (how I like it as a feature). I'll take a look at your new PR.

**Pull request closed without merging**
